namespace MusicBeePlugin
{
    partial class tabbedTagger
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabMoods1 = new System.Windows.Forms.TabPage();
            this.checkedListBox1 = new System.Windows.Forms.CheckedListBox();
            this.tabOccasions2 = new System.Windows.Forms.TabPage();
            this.checkedListBox2 = new System.Windows.Forms.CheckedListBox();
            this.tabGenres3 = new System.Windows.Forms.TabPage();
            this.checkedListBox3 = new System.Windows.Forms.CheckedListBox();
            this.tabControl1.SuspendLayout();
            this.tabMoods1.SuspendLayout();
            this.tabOccasions2.SuspendLayout();
            this.tabGenres3.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabMoods1);
            this.tabControl1.Controls.Add(this.tabOccasions2);
            this.tabControl1.Controls.Add(this.tabGenres3);
            this.tabControl1.Location = new System.Drawing.Point(12, 12);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(354, 388);
            this.tabControl1.TabIndex = 0;
            // 
            // tabMoods1
            // 
            this.tabMoods1.Controls.Add(this.checkedListBox1);
            this.tabMoods1.Location = new System.Drawing.Point(4, 22);
            this.tabMoods1.Name = "tabMoods1";
            this.tabMoods1.Padding = new System.Windows.Forms.Padding(3);
            this.tabMoods1.Size = new System.Drawing.Size(346, 362);
            this.tabMoods1.TabIndex = 0;
            this.tabMoods1.Text = "Moods";
            this.tabMoods1.UseVisualStyleBackColor = true;
            this.tabMoods1.Click += new System.EventHandler(this.tabMoods1_Click);
            // 
            // checkedListBox1
            // 
            this.checkedListBox1.FormattingEnabled = true;
            this.checkedListBox1.Items.AddRange(new object[] {
            "Abgehen",
            "Berghainstyle",
            "Cheesy",
            "Gangsta",
            "Geheimnisvoll",
            "Melancholisch",
            "Nostalgisch"});
            this.checkedListBox1.Location = new System.Drawing.Point(3, 6);
            this.checkedListBox1.Name = "checkedListBox1";
            this.checkedListBox1.Size = new System.Drawing.Size(334, 349);
            this.checkedListBox1.TabIndex = 0;
            // 
            // tabOccasions2
            // 
            this.tabOccasions2.Controls.Add(this.checkedListBox2);
            this.tabOccasions2.Location = new System.Drawing.Point(4, 22);
            this.tabOccasions2.Name = "tabOccasions2";
            this.tabOccasions2.Padding = new System.Windows.Forms.Padding(3);
            this.tabOccasions2.Size = new System.Drawing.Size(346, 362);
            this.tabOccasions2.TabIndex = 1;
            this.tabOccasions2.Text = "Occasions";
            this.tabOccasions2.UseVisualStyleBackColor = true;
            // 
            // checkedListBox2
            // 
            this.checkedListBox2.FormattingEnabled = true;
            this.checkedListBox2.Items.AddRange(new object[] {
            "BL8G32C16U4RL",
            "BL8G32C16U4WL",
            "BL2K8G32C16U4BL2K",
            "BL2K8G32C16U4RL",
            "BL2K8G32C16U4WL",
            "CMK16GX4M4C3200C16",
            "CMK16GX4M4C3200C16R",
            "CMK64GX4M8B3200C16",
            "CMW32GX4M4C3200C16 ver5.32",
            "CMT32GX4M4C3200C16 ver4.31",
            "CMT32GX4M4Z3200C16 ver5.32",
            "CMK16GX4M2Z3200C16 ver4.31",
            "CMK32GX4M2B3200C16",
            "CMK32GX4M2B3200C16R",
            "CMK32GX4M2B3200C16W",
            "CMK64GX4M4B3200C16",
            "CMK32GX4M2B3200C16 ver5.39",
            "CMK32GX4M2D3200C16 ver3.31",
            "CMT64GX4M4C3200C16 ver4.31",
            "CMW32GX4M2Z3200C16 ver3.31",
            "CMK32GX4M2Z3200C16 ver3.31",
            "CMW32GX4M2E3200C16 ver4.32",
            "CMK64GX4M2C3200C16 ver 5.49",
            "CMK128GX4M4C3200C16 ver 5.49",
            "CMT128GX4M4C3200C16 ver 3.44",
            "MD4U083216",
            "CT16G4DFD832A.16FE1",
            "CT4G4DFS632A.4FJ1",
            "CT8G4DFS832A.8FE1",
            "GP-DSG64G32",
            "F4-3200C16Q-16GRK",
            "F4-3200C16Q-32GVK",
            "F4-3200C16D-16GVKB",
            "F4-3200C14Q2-64GVK",
            "F4-3200C15Q2-64GVR",
            "F4-3200C14Q-32GFX",
            "F4-3200C16Q-32GTZR",
            "F4-3200C16Q-64GVK",
            "F4-3200C14Q-64GVK",
            "F4-3200C14Q2-128GTZ",
            "F4-3200C16Q-128GVK",
            "KVR32N22D8/16",
            "KVR32N22D8/16",
            "KVR32N22D8/32",
            "KVR32N22S6/4",
            "KVR32N22S6/4",
            "KVR32N22S8/8"});
            this.checkedListBox2.Location = new System.Drawing.Point(23, 18);
            this.checkedListBox2.MultiColumn = true;
            this.checkedListBox2.Name = "checkedListBox2";
            this.checkedListBox2.Size = new System.Drawing.Size(305, 319);
            this.checkedListBox2.TabIndex = 0;
            // 
            // tabGenres3
            // 
            this.tabGenres3.Controls.Add(this.checkedListBox3);
            this.tabGenres3.Location = new System.Drawing.Point(4, 22);
            this.tabGenres3.Name = "tabGenres3";
            this.tabGenres3.Size = new System.Drawing.Size(346, 362);
            this.tabGenres3.TabIndex = 2;
            this.tabGenres3.Text = "Genres";
            this.tabGenres3.UseVisualStyleBackColor = true;
            // 
            // checkedListBox3
            // 
            this.checkedListBox3.FormattingEnabled = true;
            this.checkedListBox3.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.checkedListBox3.Items.AddRange(new object[] {
            "2 Tone: Reggae",
            "20th Century: Classical",
            "A Capella: Other",
            "A Cappella: Other",
            "Aboriginal: World",
            "Abstract: Other",
            "Acid: Electronic",
            "Acid Breaks: Electronic",
            "Acid Electronic: Electronic",
            "Acid House: Electronic",
            "Acid Jazz: Electronic",
            "Acid Punk: Pop · Rock",
            "Acid Rock: Pop · Rock",
            "Acid Techno: Electronic",
            "Acoustic Blues: Blues · Country · Folk",
            "Acoustic Music: Other",
            "Acoustic Rock: Pop · Rock",
            "Adult Contemporary: Pop · Rock",
            "Adult Contemporary Music: Pop · Rock",
            "Adult Oriented Rock: Pop · Rock",
            "Afoxê: World",
            "African: World",
            "African Blues: World",
            "Afro Pop Music: World",
            "Afrobeat: World",
            "Afro-Cuban: Latin",
            "Afro-Cuban Jazz: Jazz",
            "Alternative Country: Blues · Country · Folk",
            "Alternative Dance: Electronic",
            "Alternative Folk: Blues · Country · Folk",
            "Alternative Hip Hop: Hip Hop",
            "Alternative Metal: Pop · Rock",
            "Alternative Pop: Pop · Rock",
            "Alternative Punk: Pop · Rock",
            "Alternative Rock: Pop · Rock",
            "Alternrock: Pop · Rock",
            "Ambient: Electronic",
            "Ambient Dub: Electronic",
            "Ambient House: Electronic",
            "Ambient Music: Electronic",
            "Ambient Techno: Electronic",
            "American Folk Music: Blues · Country · Folk",
            "Americana: Blues · Country · Folk",
            "Anarcho-Punk: Pop · Rock",
            "Andalusian Classical: World",
            "Anime: Other",
            "Anti-Folk: Blues · Country · Folk",
            "AOR: Pop · Rock",
            "Apala: World",
            "Appalachian Music: Blues · Country · Folk",
            "Arab Pop: World",
            "Arabesque: Other",
            "Arabic Pop Music: World",
            "Arena Rock: Pop · Rock",
            "Aria: Classical",
            "Art Music: Classical",
            "Art Pop: Pop · Rock",
            "Art Punk: Pop · Rock",
            "Art Rock: Pop · Rock",
            "Asian American Jazz: Jazz",
            "Atmospheric Black Metal: Pop · Rock",
            "Audiobook: Other",
            "Austro-Pop: Pop · Rock",
            "Avantgarde: Other",
            "Avant-Garde: Other",
            "Avant-Garde Jazz: Jazz",
            "Avant-Garde Metal: Pop · Rock",
            "Avant-Garde Music: Other",
            "Avant-Garde Pop: Pop · Rock",
            "Avant-Prog: Pop · Rock",
            "Axé: Latin",
            "Azonto: World",
            "Bachata: Latin",
            "Background Music: Other",
            "Baião: Latin",
            "Baithak Gana: World",
            "Bakersfield Sound: Blues · Country · Folk",
            "Balkan Pop: World",
            "Ballad: Other",
            "Ballet: Classical",
            "Ballroom: Other",
            "Baltimore Club: Electronic",
            "Bangladeshi Classical: World",
            "Barbershop: Other",
            "Baroque: Classical",
            "Baroque Era: Classical",
            "Baroque Pop: Pop · Rock",
            "Basque Music: World",
            "Bass Music: Electronic",
            "Bassline: Electronic",
            "Batucada: Latin",
            "Bayou Funk: Funk · R&B · Soul",
            "Beat: Pop · Rock",
            "Beat Music: Pop · Rock",
            "Beatbox: Hip Hop",
            "Beatdown: Pop · Rock",
            "Beautiful Music: Other",
            "Bebop: Jazz",
            "Beguine: Latin",
            "Benga: World",
            "Bengali Music: World",
            "Berlin School Of Electronic Music: Electronic",
            "Berlin-School: Electronic",
            "Bhangra: World",
            "Big Band: Jazz",
            "Big Beat: Electronic",
            "Bikutsi: World",
            "Bitcore: Electronic",
            "Black Metal: Pop · Rock",
            "Blackened Death Metal: Pop · Rock",
            "Blackgaze: Pop · Rock",
            "Blue-Eyed Soul: Funk · R&B · Soul",
            "Bluegrass: Blues · Country · Folk",
            "Bluegrass Music: Blues · Country · Folk",
            "Blues: Blues · Country · Folk",
            "Blues Rock: Pop · Rock",
            "Blues-Rock: Pop · Rock",
            "Bolero: Latin",
            "Bolero Son: Latin",
            "Bollywood: Other",
            "Bomba: Latin",
            "Bongo Flava: World",
            "Boogaloo: Latin",
            "Boogie: Other",
            "Boogie Rock: Pop · Rock",
            "Boogie Woogie: Blues · Country · Folk",
            "Boogie-Woogie: Blues · Country · Folk",
            "Boom Bap: Hip Hop",
            "Booty Bass: Hip Hop",
            "Bop: Jazz",
            "Bossa Nova: Latin",
            "Bounce: Hip Hop",
            "Boy Band: Pop · Rock",
            "Brass & Military: Other",
            "Brass Band: Other",
            "Brazilian Rock: World",
            "Breakbeat: Electronic",
            "Breakbeat Hardcore: Electronic",
            "Breakcore: Electronic",
            "Breaks: Electronic",
            "Brit Pop: Pop · Rock",
            "Britcore: Hip Hop",
            "British Blues: Blues · Country · Folk",
            "Britpop: Pop · Rock",
            "Broken Beat: Other",
            "Brutal Death Metal: Pop · Rock",
            "Bubblegum: Pop · Rock",
            "Bubblegum Pop: Pop · Rock",
            "Bubbling: Electronic",
            "Bubbling House: Electronic",
            "Cabaret: Other",
            "Cajun: Blues · Country · Folk",
            "Calypso: World",
            "Calypso Jazz: World",
            "Calypso Music: World",
            "Cambodian Classical: World",
            "Candombe: Latin",
            "Cantata: Classical",
            "Canterbury Scene: Pop · Rock",
            "Cantopop: World",
            "Canzone Napoletana: World",
            "Cape Jazz: Jazz",
            "Carimbó: Latin",
            "Carnatic: World",
            "Catalan Music: World",
            "Celtic: World",
            "Celtic Music: World",
            "Celtic Punk: Pop · Rock",
            "Chacarera: World",
            "Cha-Cha: Other",
            "Cha-Cha-Chá: Other",
            "Chalga: World",
            "Chamamé: World",
            "Chamber Jazz: Jazz",
            "Chamber Music: Classical",
            "Chamber Pop: Pop · Rock",
            "Champeta: Latin",
            "Changüí: World",
            "Chanson: World",
            "Charanga: Latin",
            "Chicago Blues: Blues · Country · Folk",
            "Chicano Rap: Hip Hop",
            "Chicano Rock: World",
            "Children’s: Other",
            "Chillout: Other",
            "Chill-Out Music: Pop · Rock",
            "Chillwave: Electronic",
            "Chimurenga: World",
            "Chinese Classical: World",
            "Chinese Pop: World",
            "Chinese Rock: World",
            "Chiptune: Electronic",
            "Choral: Classical",
            "Choro: Latin",
            "Christian Gangsta Rap: Hip Hop",
            "Christian Metal: Pop · Rock",
            "Christian Rap: Hip Hop",
            "Christian Rock: Pop · Rock",
            "Christmas: Other",
            "Christmas Music: Other",
            "Church Cantata: Classical",
            "Chutney: World",
            "Chutney Soca: World",
            "City Pop: World",
            "Classic Blues: Blues · Country · Folk",
            "Classic Country: Blues · Country · Folk",
            "Classic Jazz: Jazz",
            "Classic Rock: Pop · Rock",
            "Classic Trance: Electronic",
            "Classical: Classical",
            "Classical Crossover: Pop · Rock",
            "Classical Music: Classical",
            "Close Harmony: Other",
            "Cloud Rap: Hip Hop",
            "Club: Electronic",
            "Club Jazz: Electronic",
            "Club-House: Electronic",
            "Cobla: World",
            "Coldwave: Pop · Rock",
            "College Rock: Pop · Rock",
            "Comedy: Other",
            "Comedy Rock: Pop · Rock",
            "Compas: Latin",
            "Concerto: Classical",
            "Conjunto: Latin",
            "Conscious Hip Hop: Hip Hop",
            "Contemporary: Other",
            "Contemporary Christian: Pop · Rock",
            "Contemporary Christian Music: Pop · Rock",
            "Contemporary Classical: Classical",
            "Contemporary Classical Music: Classical",
            "Contemporary Country: Blues · Country · Folk",
            "Contemporary Folk: Blues · Country · Folk",
            "Contemporary Folk Music: Blues · Country · Folk",
            "Contemporary Gospel: Blues · Country · Folk",
            "Contemporary Jazz: Jazz",
            "Contemporary R&B: Funk · R&B · Soul",
            "Contra: Other",
            "Cool Jazz: Jazz",
            "Copla: World",
            "Corrido: Latin",
            "Country: Blues · Country · Folk",
            "Country Blues: Blues · Country · Folk",
            "Country Folk: Blues · Country · Folk",
            "Country Music: Blues · Country · Folk",
            "Country Pop: Blues · Country · Folk",
            "Country Rap: Pop · Rock",
            "Country Rock: Pop · Rock",
            "Countrypolitan: Blues · Country · Folk",
            "Coupé-Décalé: World",
            "Cowpunk: Pop · Rock",
            "Crossover: Other",
            "Crossover Jazz: Jazz",
            "Crossover Prog: Pop · Rock",
            "Crossover Thrash Metal: Pop · Rock",
            "Crunk: Hip Hop",
            "Crust: Pop · Rock",
            "Crust Punk: Pop · Rock",
            "Cuatro: Latin",
            "Cubano: Latin",
            "Cumbia: Latin",
            "Cumbia Villera: World",
            "Cyberpunk: Pop · Rock",
            "Dance: Other",
            "Dance Music: Other",
            "Dance Pop: Pop · Rock",
            "Dancehall: Reggae",
            "Dancehall, DJ-Ing: Electronic",
            "Dance-Pop: Pop · Rock",
            "Dance-Punk: Pop · Rock",
            "Dance-Rock: Pop · Rock",
            "Dangdut: World",
            "Danzon: Latin",
            "Dark Ambient: Electronic",
            "Dark Cabaret: Pop · Rock",
            "Dark Electro: Pop · Rock",
            "Dark Folk: Blues · Country · Folk",
            "Dark Wave: Pop · Rock",
            "Darkcore: Electronic",
            "Darkwave: Pop · Rock",
            "D-Beat: Pop · Rock",
            "Death Metal: Pop · Rock",
            "Deathcore: Pop · Rock",
            "Death-Doom Metal: Pop · Rock",
            "Deathgrind: Pop · Rock",
            "Deathrock: Pop · Rock",
            "Deconstructed Club: Pop · Rock",
            "Deep Funk: Funk · R&B · Soul",
            "Deep House: Electronic",
            "Deep Soul: Funk · R&B · Soul",
            "Deep Techno: Electronic",
            "Delta Blues: Blues · Country · Folk",
            "Depressive Black Metal: Pop · Rock",
            "Descarga: Latin",
            "Desert Blues: World",
            "Desert Rock: Pop · Rock",
            "Detroit Techno: Electronic",
            "Digital Hardcore: Pop · Rock",
            "Dirty Rap: Hip Hop",
            "Disco: Pop · Rock",
            "Disco Polo: Pop · Rock",
            "Dixieland: Jazz",
            "Djent: Pop · Rock",
            "Donk: Electronic",
            "Doom Metal: Pop · Rock",
            "Doomcore: Electronic",
            "Doo-Wop: Funk · R&B · Soul",
            "Downtempo: Electronic",
            "Dream Pop: Pop · Rock",
            "Drill: Hip Hop",
            "Drill And Bass: Electronic",
            "Drill \'n\' Bass: Electronic",
            "Drone: Other",
            "Drone Metal: Pop · Rock",
            "Drone Music: Other",
            "Drum And Bass: Electronic",
            "Drum N Bass: Electronic",
            "Dub: Reggae",
            "Dub Poetry: Reggae",
            "Dub Techno: Electronic",
            "Dubstep: Electronic",
            "Dubtronica: Electronic",
            "Dungeon Synth: Electronic",
            "Early: Classical",
            "Early Music: Classical",
            "Early Romantic: Classical",
            "East Coast Blues: Blues · Country · Folk",
            "East Coast Hip Hop: Hip Hop",
            "East Coast Swing: Other",
            "Easy Listening: Other",
            "EBM: Electronic",
            "EDM: Electronic",
            "Education: Other",
            "Educational: Other",
            "Electric Blues: Blues · Country · Folk",
            "Electro: Electronic",
            "Electro House: Electronic",
            "Electro Swing: Electronic",
            "Electroclash: Electronic",
            "Electro-Funk: Electronic",
            "Electro-Hop: Electronic",
            "Electro-House: Electronic",
            "Electro-Industrial: Pop · Rock",
            "Electronic: Electronic",
            "Electronic Dance Music: Electronic",
            "Electronic Music: Electronic",
            "Electronic Rock: Pop · Rock",
            "Electronica: Electronic",
            "Electronicore: Pop · Rock",
            "Electropop: Pop · Rock",
            "Electro-Pop: Pop · Rock",
            "Electropunk: Pop · Rock",
            "Emo: Pop · Rock",
            "Emocore: Pop · Rock",
            "Enka: World",
            "Éntekhno: World",
            "Ethereal: Pop · Rock",
            "Ethereal Wave: Pop · Rock",
            "Ethnic: World",
            "Ethno-Pop: Pop · Rock",
            "Étude: Classical",
            "Euro Disco: Pop · Rock",
            "Euro House: Electronic",
            "Euro Trance: Electronic",
            "Eurobeat: Pop · Rock",
            "Eurodance: Electronic",
            "Euro-Dance: Electronic",
            "Euro-Disco: Pop · Rock",
            "Euro-House: Electronic",
            "Europop: Pop · Rock",
            "Euro-Techno: Electronic",
            "Exotica: World",
            "Experimental: Other",
            "Experimental Music: Other",
            "Experimental Pop: Pop · Rock",
            "Experimental Rock: Pop · Rock",
            "Fado: World",
            "Favela Funk: World",
            "Field Recording: Other",
            "Fife And Drum Blues: Blues · Country · Folk",
            "Filk: Other",
            "Film Score: Other",
            "Flamenco: World",
            "Flashcore: Electronic",
            "Folk: Blues · Country · Folk",
            "Folk Jazz: Blues · Country · Folk",
            "Folk Metal: Pop · Rock",
            "Folk Music: Blues · Country · Folk",
            "Folk Pop: Pop · Rock",
            "Folk Punk: Pop · Rock",
            "Folk Rock: Pop · Rock",
            "Folklore: World",
            "Folk-Pop: Blues · Country · Folk",
            "Folktronica: Electronic",
            "Forró: Latin",
            "Foxtrot: Other",
            "Freak Folk: Blues · Country · Folk",
            "Free Funk: Jazz",
            "Free Improvisation: Other",
            "Free Jazz: Jazz",
            "Freestyle: Pop · Rock",
            "French House: Electronic",
            "French Pop: World",
            "French Pop Music: Pop · Rock",
            "French Rock: Pop · Rock",
            "Fuji: World",
            "Funaná: World",
            "Funeral Doom Metal: Pop · Rock",
            "Funk: Funk · R&B · Soul",
            "Funk Carioca: World",
            "Funk Metal: Pop · Rock",
            "Funk Rock: Pop · Rock",
            "Funk Soul: Funk · R&B · Soul",
            "Funkot: World",
            "Funky House: Electronic",
            "Furniture Music: Other",
            "Fusion: Jazz",
            "Future Garage: Electronic",
            "Future Jazz: Electronic",
            "Futurepop: Electronic",
            "Gabba: Electronic",
            "Gabber: Electronic",
            "Gagaku: World",
            "Gaita: Latin",
            "Gamelan: World",
            "Gangsta: Hip Hop",
            "Gangsta Rap: Hip Hop",
            "Garage: Electronic",
            "Garage House: Electronic",
            "Garage Punk: Pop · Rock",
            "Garage Rock: Pop · Rock",
            "G-Funk: Hip Hop",
            "Ghazal: World",
            "Ghetto: Hip Hop",
            "Ghetto House: Electronic",
            "Ghettotech: Electronic",
            "Girl Group: Pop · Rock",
            "Glam: Pop · Rock",
            "Glam Metal: Pop · Rock",
            "Glam Rock: Pop · Rock",
            "Glamrock: Pop · Rock",
            "Glitch: Electronic",
            "Goa: Electronic",
            "Goa Trance: Electronic",
            "Gogo: Funk · R&B · Soul",
            "Go-Go: Funk · R&B · Soul",
            "Goregrind: Pop · Rock",
            "Gospel: Blues · Country · Folk",
            "Gospel Music: Blues · Country · Folk",
            "Goth Rock: Pop · Rock",
            "Gothic: Pop · Rock",
            "Gothic Metal: Pop · Rock",
            "Gothic Rock: Pop · Rock",
            "Grebo: World",
            "Greek Entechno: World",
            "Greek Laika: World",
            "Gregorian Chant: Other",
            "Grime: Electronic",
            "Grindcore: Pop · Rock",
            "Griot: World",
            "Groove Metal: Pop · Rock",
            "Group Sounds: World",
            "Grunge: Pop · Rock",
            "Guaguancó: Latin",
            "Guajira: Latin",
            "Guaracha: Latin",
            "Guarania: World",
            "Gypsy Jazz: Jazz",
            "Hands Up: Electronic",
            "Happy Hardcore: Electronic",
            "Hard Beat: Electronic",
            "Hard Bop: Jazz",
            "Hard House: Electronic",
            "Hard Rock: Pop · Rock",
            "Hard Techno: Electronic",
            "Hard Trance: Electronic",
            "Hardbag: Electronic",
            "Hardcore: Electronic",
            "Hardcore Hip Hop: Hip Hop",
            "Hardcore Hip-Hop: Hip Hop",
            "Hardcore Punk: Pop · Rock",
            "Hardcore Techno: Electronic",
            "Hardstyle: Electronic",
            "Hardstyle Trance: Electronic",
            "Harmonica Blues: Blues · Country · Folk",
            "Harsh Noise: Pop · Rock",
            "Harsh Noise Wall: Pop · Rock",
            "Hauntology: Electronic",
            "Hawaiian: World",
            "Heartland Rock: Pop · Rock",
            "Heavy Metal: Pop · Rock",
            "Heavy Psych: Pop · Rock",
            "Heavy Rock: Pop · Rock",
            "Hi Nrg: Pop · Rock",
            "Highlife: World",
            "Hillbilly: Blues · Country · Folk",
            "Hindustani: World",
            "Hindustani Classical Music: World",
            "Hi-Nrg: Pop · Rock",
            "Hip Hop: Hip Hop",
            "Hip Hop Music: Hip Hop",
            "Hip Hop Soul: Funk · R&B · Soul",
            "Hip House: Electronic",
            "Hip-Hop: Hip Hop",
            "Hip-Hop Soul: Funk · R&B · Soul",
            "Hip-House: Electronic",
            "Hiplife: Hip Hop",
            "Hong Kong And Cantonese Pop: World",
            "Hong Kong English Pop: World",
            "Honky Tonk: Blues · Country · Folk",
            "Horror Punk: Pop · Rock",
            "Horror Rock: Pop · Rock",
            "Horrorcore: Hip Hop",
            "House: Electronic",
            "House Music: Electronic",
            "Humor: Other",
            "Hyphy: Hip Hop",
            "IDM: Electronic",
            "Illbient: Electronic",
            "Impressionist: Classical",
            "Indian Classical: World",
            "Indian Classical Music: World",
            "Indian Pop: World",
            "Indie: Pop · Rock",
            "Indie Folk: Blues · Country · Folk",
            "Indie Pop: Pop · Rock",
            "Indie Rock: Pop · Rock",
            "Indietronica: Electronic",
            "Indigenous Music: World",
            "Indonesian Pop: World",
            "Indorock: Pop · Rock",
            "Industrial: Other",
            "Industrial Metal: Pop · Rock",
            "Industrial Music: Other",
            "Industrial Rock: Pop · Rock",
            "Industrial Techno: Electronic",
            "Instrumental: Other",
            "Instrumental Jazz: Jazz",
            "Instrumental Pop: Pop · Rock",
            "Instrumental Rock: Pop · Rock",
            "Intelligent Dance Music: Electronic",
            "Interview: Other",
            "Iranian Pop: World",
            "Irish Folk: World",
            "Irish Traditional Music: World",
            "Isicathamiya: World",
            "Italo Dance: Pop · Rock",
            "Italo Disco: Pop · Rock",
            "Italo House: Pop · Rock",
            "Italodance: Pop · Rock",
            "Italo-Disco: Pop · Rock",
            "Jam Band: Pop · Rock",
            "Jangle Pop: Pop · Rock",
            "Japanese Pop: World",
            "Jazz: Jazz",
            "Jazz Blues: Blues · Country · Folk",
            "Jazz Fusion: Jazz",
            "Jazz Pop: Pop · Rock",
            "Jazz Rap: Hip Hop",
            "Jazz Rock: Jazz",
            "Jazz Standard: Jazz",
            "Jazz Waltz: Jazz",
            "Jazzdance: Other",
            "Jazz-Funk: Jazz",
            "Jazz-Rock: Jazz",
            "Jazzy Hip-Hop: Hip Hop",
            "J-Core: Electronic",
            "Jibaro: Latin",
            "Jit: World",
            "Jive: Other",
            "Joik: World",
            "Joropo: Latin",
            "Jota: World",
            "J-Pop: World",
            "J-Rock: World",
            "Juju: World",
            "Juke: Electronic",
            "Jump Blues: Blues · Country · Folk",
            "Jumpstyle: Electronic",
            "Jungle: Electronic",
            "Junkanoo: World",
            "Karaoke: Other",
            "Kaseko: World",
            "Kawaii Metal: World",
            "Kayōkyoku: World",
            "Keroncong: World",
            "Kizomba: World",
            "Klasik: World",
            "Klezmer: World",
            "Kompa: World",
            "Korean Court Music: World",
            "Korean Pop: World",
            "K-Pop: World",
            "Krautrock: Pop · Rock",
            "Kuduro: World",
            "Kwaito: World",
            "Kwela: World",
            "Laïko: World",
            "Laïkó: World",
            "Lambada: Latin",
            "Lao Music: World",
            "Latin: Latin",
            "Latin American Music: Latin",
            "Latin Ballad: Latin",
            "Latin Jazz: Jazz",
            "Latin Music: Latin",
            "Latin Pop: World",
            "Latin R&B: Latin",
            "Latin Rap: World",
            "Latin Rock: Pop · Rock",
            "Latin Soul: Latin",
            "Leftfield: Other",
            "Lento Violento: Pop · Rock",
            "Levenslied: World",
            "Light Music: Other",
            "Line Dance: Blues · Country · Folk",
            "Liscio: World",
            "Liturgical Music: Other",
            "Lo-Fi: Other",
            "Lo-Fi Music: Other",
            "Louisiana Blues: Blues · Country · Folk",
            "Louisiana Swamp Pop: Blues · Country · Folk",
            "Lounge: Other",
            "Lounge Music: Other",
            "Lovers Rock: Reggae",
            "Low Fidelity: Other",
            "Lowercase: Electronic",
            "Luk Krung: World",
            "Luk Thung: World",
            "Lullaby: Other",
            "Madchester: Pop · Rock",
            "Madrigal: Classical",
            "Mainstream: Other",
            "Mainstream Jazz: Jazz",
            "Mainstream Rock: Pop · Rock",
            "Makina: Electronic",
            "Makossa: World",
            "Maloya: World",
            "Mambo: Latin",
            "Mandarin Pop: World",
            "Mandopop: World",
            "Mangue Bit: World",
            "March: Other",
            "Marcha Carnavalesca: Latin",
            "Marches: Other",
            "Mariachi: Latin",
            "Marimba: Latin",
            "Marrabenta: World",
            "Martial Industrial: Pop · Rock",
            "Martial Music: Other",
            "Maskanda: World",
            "Mass: Classical",
            "Math Rock: Pop · Rock",
            "Mathcore: Pop · Rock",
            "Mbalax: World",
            "Mbaqanga: World",
            "M-Base: Other",
            "Mbube: World",
            "Medieval: Classical",
            "Meditative: Other",
            "Melodic Black Metal: Pop · Rock",
            "Melodic Death Metal: Pop · Rock",
            "Melodic Hardcore: Pop · Rock",
            "Melodic Metalcore: Pop · Rock",
            "Melodic Rock: Pop · Rock",
            "Melodic Trance: Electronic",
            "Memphis Blues: Blues · Country · Folk",
            "Mento: World",
            "Merengue: Latin",
            "Metal: Pop · Rock",
            "Metalcore: Pop · Rock",
            "Mexican Pop: World",
            "Miami Bass: Hip Hop",
            "Microhouse: Electronic",
            "Middle Of The Road: Other",
            "Midwest Hip Hop: Hip Hop",
            "Midwest Hip-Hop: Hip Hop",
            "Military: Other",
            "Milonga: World",
            "Mincecore: Pop · Rock",
            "Mini-Jazz: World",
            "Minimal: Other",
            "Minimal Music: Other",
            "Minimal Techno: Electronic",
            "Minimal Wave: Electronic",
            "Minimalism: Other",
            "Minimalist: Other",
            "Minneapolis Sound: Funk · R&B · Soul",
            "Min\'yo: World",
            "Min\'yō: World",
            "Mizrahi: World",
            "Mizrahi Music: World",
            "Mod: Pop · Rock",
            "Modal Jazz: Jazz",
            "Modern: Classical",
            "Modern Blues: Blues · Country · Folk",
            "Modern Classical: Classical",
            "Modern Country: Blues · Country · Folk",
            "Modern Electric Blues: Blues · Country · Folk",
            "Modern Jazz: Jazz",
            "Mor Lam Sing: World",
            "Morna: World",
            "Motet: Classical",
            "Motown: Funk · R&B · Soul",
            "Motswako: World",
            "Mouth Music: World",
            "Movie Effects: Other",
            "MPB: Latin",
            "Mugham: World",
            "Musette: Latin",
            "Museve: World",
            "Music Hall: Other",
            "Música Criolla: Latin",
            "Musica Popular Brasileira: Latin",
            "Música Popular Brasileira: Latin",
            "Musical: Other",
            "Musical Improvisation: Other",
            "Musical Theater: Other",
            "Musique Concrète: Electronic",
            "Nashville Sound: Blues · Country · Folk",
            "National Anthem: Other",
            "National Folk: World",
            "Native American: Blues · Country · Folk",
            "NDW: Pop · Rock",
            "Neapolitan Song: World",
            "Nederlandstalig: World",
            "Nederpop: World",
            "Neder-Pop: World",
            "Néo Kyma: World",
            "Neo Soul: Funk · R&B · Soul",
            "Neo Trance: Electronic",
            "Neo-Classical: Classical",
            "Neo-Classical Metal: Pop · Rock",
            "Neoclassical New-Age Music: Other",
            "Neofolk: Blues · Country · Folk",
            "Neo-Prog: Pop · Rock",
            "Neo-Progressive Rock: Pop · Rock",
            "Neo-Psychedelia: Pop · Rock",
            "Neo-Rockabilly: Pop · Rock",
            "Neo-Romantic: Classical",
            "Neo-Traditional Country: Blues · Country · Folk",
            "Neo-Traditionalist Country: Blues · Country · Folk",
            "Népzene: World",
            "Nerdcore: Hip Hop",
            "Nerdcore Techno: Electronic",
            "Neue Deutsche Härte: Pop · Rock",
            "Neue Deutsche Welle: Pop · Rock",
            "New Age: Other",
            "New Beat: Electronic",
            "New Flamenco: World",
            "New Jack Swing: Funk · R&B · Soul",
            "New Prog: Pop · Rock",
            "New Romantic: Pop · Rock",
            "New Romanticism: Pop · Rock",
            "New Wave: Pop · Rock",
            "New-Age Music: Other",
            "Nightcore: Electronic",
            "No Wave: Pop · Rock",
            "Noise: Pop · Rock",
            "Noise Music: Pop · Rock",
            "Noise Pop: Pop · Rock",
            "Noise Rock: Pop · Rock",
            "Noisecore: Pop · Rock",
            "Non-Music: Other",
            "Nordic: World",
            "Norteño: Latin",
            "Northern Soul: Funk · R&B · Soul",
            "Novelty: Other",
            "Nu Jazz: Electronic",
            "Nu Metal: Pop · Rock",
            "Nu-Disco: Electronic",
            "Nueva Cancion: World",
            "Nueva Canción: World",
            "Nueva Trova: Latin",
            "Nuevo Tango: Latin",
            "Nu-Funk: Funk · R&B · Soul",
            "Nursery Rhymes: Other",
            "Occitan: Latin",
            "Occult Rock: Pop · Rock",
            "Oi: Pop · Rock",
            "Old School Death Metal: Pop · Rock",
            "Oldies: Other",
            "Old-School Hip Hop: Hip Hop",
            "Old-School Rap: Hip Hop",
            "Old-Time: Blues · Country · Folk",
            "Opera: Classical",
            "Operatic Pop: Pop · Rock",
            "Operetta: Classical",
            "Oratorio: Classical",
            "Orchestral: Classical",
            "Orchestral Jazz: Jazz",
            "Ottoman Classical: World",
            "Ottoman Classical Music: World",
            "Outlaw Country: Blues · Country · Folk",
            "Outsider Music: Other",
            "Overtone Singing: World",
            "Overture: Classical",
            "P.Funk: Funk · R&B · Soul",
            "Pachanga: Latin",
            "Pacific: World",
            "Paisley Underground: Pop · Rock",
            "Palm-Wine: World",
            "Parlour Music: Pop · Rock",
            "Parody: Other",
            "Pasodoble: World",
            "Performance Art: Other",
            "Period › 20th Century: Classical",
            "Period › Baroque: Classical",
            "Period › Classical: Classical",
            "Period › Contemporary: Classical",
            "Period › Early Romantic: Classical",
            "Period › Late Romantic: Classical",
            "Period › Renaissance: Classical",
            "Persian Classical: World",
            "P-Funk: Funk · R&B · Soul",
            "Philadelphia Soul: Funk · R&B · Soul",
            "Philippine Classical: World",
            "Phleng Phuea Chiwit: World",
            "Piano Blues: Blues · Country · Folk",
            "Piano Rock: Pop · Rock",
            "Piedmont Blues: Blues · Country · Folk",
            "Pinoy Pop: World",
            "Piobaireachd: World",
            "Pipe & Drum: Other",
            "Plena: Latin",
            "Poetry: Other",
            "Political: Other",
            "Political Hip Hop: Hip Hop",
            "Political Hip-Hop: Hip Hop",
            "Polka: World",
            "Pop: Pop · Rock",
            "Pop Art: Pop · Rock",
            "Pop Folk: Blues · Country · Folk",
            "Pop Metal: Pop · Rock",
            "Pop Music: Pop · Rock",
            "Pop Punk: Pop · Rock",
            "Pop Rap: Hip Hop",
            "Pop Rock: Pop · Rock",
            "Pop Soul: Funk · R&B · Soul",
            "Pop-Music: Pop · Rock",
            "Popular Music: Pop · Rock",
            "Pornocore: Hip Hop",
            "Pornogrind: Pop · Rock",
            "Porro: Latin",
            "Post-Bop: Jazz",
            "Post-Britpop: Pop · Rock",
            "Post-Classical: Classical",
            "Post-Club: Pop · Rock",
            "Post-Disco: Pop · Rock",
            "Post-Grunge: Pop · Rock",
            "Post-Hardcore: Pop · Rock",
            "Post-Industrial: Pop · Rock",
            "Post-Industrial Music: Pop · Rock",
            "Post-Metal: Pop · Rock",
            "Post-Modern: Classical",
            "Post-Progressive: Pop · Rock",
            "Post-Punk: Pop · Rock",
            "Post-Punk Revival: Pop · Rock",
            "Post-Rock: Pop · Rock",
            "Power Ballad: Other",
            "Power Electronics: Pop · Rock",
            "Power Metal: Pop · Rock",
            "Power Noise: Pop · Rock",
            "Power Pop: Pop · Rock",
            "Powerviolence: Pop · Rock",
            "Production Music: Other",
            "Prog Rock: Pop · Rock",
            "Progressive: Other",
            "Progressive Bluegrass: Blues · Country · Folk",
            "Progressive Breaks: Electronic",
            "Progressive Country: Blues · Country · Folk",
            "Progressive Death Metal: Pop · Rock",
            "Progressive Electronic: Electronic",
            "Progressive Folk: Blues · Country · Folk",
            "Progressive Folk Music: Blues · Country · Folk",
            "Progressive House: Electronic",
            "Progressive Metal: Pop · Rock",
            "Progressive Music: Other",
            "Progressive Pop: Pop · Rock",
            "Progressive Rock: Pop · Rock",
            "Progressive Trance: Electronic",
            "Prog-Rock: Pop · Rock",
            "Promotional: Other",
            "Protest Song: Other",
            "Proto-Prog: Pop · Rock",
            "Protopunk: Pop · Rock",
            "Proto-Punk: Pop · Rock",
            "Psychedelia: Pop · Rock",
            "Psychedelic: Other",
            "Psychedelic Folk: Blues · Country · Folk",
            "Psychedelic Funk: Funk · R&B · Soul",
            "Psychedelic Music: Other",
            "Psychedelic Pop: Pop · Rock",
            "Psychedelic Rock: Pop · Rock",
            "Psychedelic Soul: Funk · R&B · Soul",
            "Psychedelic Trance: Electronic",
            "Psychobilly: Pop · Rock",
            "Psytrance: Electronic",
            "Psy-Trance: Electronic",
            "Pub Rock: Pop · Rock",
            "Public Broadcast: Other",
            "Punk: Pop · Rock",
            "Punk Blues: Pop · Rock",
            "Punk Rock: Pop · Rock",
            "Qawwali: World",
            "Quechua: Latin",
            "Queercore: Pop · Rock",
            "Quickstep: Other",
            "Quiet Storm: Funk · R&B · Soul",
            "R&B: Funk · R&B · Soul",
            "Radioplay: Other",
            "Raga Rock: World",
            "Ragga: Reggae",
            "ragga Hip-Hop: Hip Hop",
            "Ragga Hiphop: Hip Hop",
            "Ragga Jungle: Electronic",
            "Ragtime: Jazz",
            "Raï: World",
            "Ranchera: Latin",
            "Rap: Hip Hop",
            "Rap Metal: Pop · Rock",
            "Rap Rock: Pop · Rock",
            "Rapcore: Pop · Rock",
            "Rapping: Hip Hop",
            "Rapso: World",
            "Rautalanka: World",
            "Rave: Electronic",
            "Rebetiko: World",
            "Reggae: Reggae",
            "Reggae Fusion: Reggae",
            "Reggae Gospel: Reggae",
            "Reggae Rock: Pop · Rock",
            "Reggaefusion: Reggae",
            "Reggae-Pop: Reggae",
            "Reggaeton: Latin",
            "Religious: Other",
            "Religious Music: Other",
            "Renaissance: Classical",
            "Rhythm & Blues: Blues · Country · Folk",
            "Rhythm And Blues: Funk · R&B · Soul",
            "Rhythmic Noise: Pop · Rock",
            "Rhythmic Soul: Funk · R&B · Soul",
            "Ritual Ambient: Electronic",
            "Rock: Pop · Rock",
            "Rock & Roll: Pop · Rock",
            "Rock And Roll: Pop · Rock",
            "Rock En Español: World",
            "Rock Music: Pop · Rock",
            "Rock Opera: Pop · Rock",
            "Rock Pop: Pop · Rock",
            "Rockabilly: Pop · Rock",
            "Rocksteady: Reggae",
            "Romani: World",
            "Romantic: Classical",
            "Romantic Classical: Classical",
            "Romantic Era: Classical",
            "Roots Reggae: Reggae",
            "Roots Rock: Pop · Rock",
            "Rumba: Latin",
            "Rune Singing: World",
            "Russian Pop: World",
            "Ryūkōka: World",
            "Sadcore: Pop · Rock",
            "Sakara: World",
            "Salegy: World",
            "Salsa: Latin",
            "Samba: Latin",
            "Samba Reggae: World",
            "Samba-Canção: Latin",
            "Samba-Funk: World",
            "Samba-Reggae: World",
            "Samba-Rock: World",
            "Sámi Music: World",
            "Satire: Other",
            "Scat: Jazz",
            "Schlager: World",
            "Schlager Music: World",
            "Schranz: Electronic",
            "Score: Other",
            "Screamo: Pop · Rock",
            "Screw: Hip Hop",
            "Sea Shanties: World",
            "Séga: World",
            "Sephardic: World",
            "Sephardic Music: World",
            "Seresta: Latin",
            "Serial: Classical",
            "Shibuya-Kei: World",
            "Shock Rock: Pop · Rock",
            "Shoegaze: Pop · Rock",
            "Shoegazing: Pop · Rock",
            "Show Tune: Other",
            "Singer-Songwriter: Pop · Rock",
            "Ska: Reggae",
            "Ska Punk: Pop · Rock",
            "Skacore: Pop · Rock",
            "Skiffle: Blues · Country · Folk",
            "Skweee: Electronic",
            "Slow Jam: Funk · R&B · Soul",
            "Slow Rock: Pop · Rock",
            "Slow Waltz: Other",
            "Slowcore: Pop · Rock",
            "Sludge Metal: Pop · Rock",
            "Smooth Jazz: Jazz",
            "Smooth Soul: Funk · R&B · Soul",
            "Soca: World",
            "Soft Rock: Pop · Rock",
            "Son: Latin",
            "Son Cubano: World",
            "Son Montuno: Latin",
            "Sonata: Classical",
            "Sonero: Latin",
            "Song-Cycle: Classical",
            "Sophisti-Pop: Pop · Rock",
            "Soukous: World",
            "Soul: Funk · R&B · Soul",
            "Soul Blues: Blues · Country · Folk",
            "Soul Jazz: Jazz",
            "Soul Music: Funk · R&B · Soul",
            "Sound Art: Other",
            "Sound Collage: Other",
            "Sound Poetry: Other",
            "Soundtrack: Other",
            "Southern Gothic: Blues · Country · Folk",
            "Southern Hip Hop: Hip Hop",
            "Southern Hip-Hop: Hip Hop",
            "Southern Rock: Pop · Rock",
            "Southern Soul: Funk · R&B · Soul",
            "Space: Other",
            "Space Age Pop: Pop · Rock",
            "Space Disco: Pop · Rock",
            "Space Music: Other",
            "Space Rock: Pop · Rock",
            "Space-Age: Pop · Rock",
            "Special Effects: Other",
            "Speech: Other",
            "Speed Garage: Electronic",
            "Speed Metal: Pop · Rock",
            "Speedcore: Electronic",
            "Spiritual: Blues · Country · Folk",
            "Spoken Word: Other",
            "Stage & Screen: Other",
            "Stage And Screen: Other",
            "Steampunk: Other",
            "Steel Band: World",
            "Stoner Metal: Pop · Rock",
            "Stoner Rock: Pop · Rock",
            "Story: Other",
            "Straight-Ahead Jazz: Jazz",
            "Street Punk: Pop · Rock",
            "Stride: Jazz",
            "Suite: Classical",
            "Sunshine Pop: Pop · Rock",
            "Surf: Pop · Rock",
            "Surf Music: Pop · Rock",
            "Surf Pop: Pop · Rock",
            "Surf Rock: Pop · Rock",
            "Swamp Pop: Pop · Rock",
            "Swamp Rock: Pop · Rock",
            "Swedish Ballad Tradition: World",
            "Swing: Jazz",
            "Swing Music: Jazz",
            "Swingbeat: Funk · R&B · Soul",
            "Symphonic Black Metal: Pop · Rock",
            "Symphonic Metal: Pop · Rock",
            "Symphonic Music: Classical",
            "Symphonic Poem: Classical",
            "Symphonic Prog: Pop · Rock",
            "Symphonic Rock: Pop · Rock",
            "Symphony: Classical",
            "Synthpop: Pop · Rock",
            "Synth-Pop: Pop · Rock",
            "Synthpunk: Pop · Rock",
            "Synthwave: Electronic",
            "Taarab: World",
            "Tacsonamaidh Aileag: World",
            "Taiwanese Pop: World",
            "Tango: Latin",
            "Tech House: Electronic",
            "Tech Trance: Electronic",
            "Technical Death Metal: Pop · Rock",
            "Techno: Electronic",
            "Techno-Industrial: Electronic",
            "Teen Pop: Pop · Rock",
            "Tejano: Latin",
            "Tejano Music: Latin",
            "Terror: Electronic",
            "Terrorcore: Electronic",
            "Texas Blues: Blues · Country · Folk",
            "Thai Classical: World",
            "Thai Pop: World",
            "Theme: Other",
            "Therapy: Other",
            "Third Stream: Other",
            "Thrash: Pop · Rock",
            "Thrash Metal: Pop · Rock",
            "Thrashcore: Pop · Rock",
            "Thug Rap: Hip Hop",
            "Timba: Latin",
            "Top 40: Other",
            "Trad Jazz: Jazz",
            "Traditional Bluegrass: Blues · Country · Folk",
            "Traditional Country: Blues · Country · Folk",
            "Traditional Folk: Blues · Country · Folk",
            "Traditional Heavy Metal: Pop · Rock",
            "Traditional Pop Music: Pop · Rock",
            "Traditional Song: World",
            "Trance: Electronic",
            "Trancecore: Pop · Rock",
            "Trap: Hip Hop",
            "Trap [edm]: Electronic",
            "Tribal: Other",
            "Tribal Ambient: Electronic",
            "Tribal House: Electronic",
            "Trip Hop: Electronic",
            "Trip-Hop: Electronic",
            "Tropical House: Electronic",
            "Tropicália: World",
            "Tropicalismo: World",
            "Trova: Latin",
            "Turkish Pop: World",
            "Turntablism: Hip Hop",
            "Tuvan Throat Singing: World",
            "Twelve-Tone: Other",
            "Twist: Pop · Rock",
            "UK Drill: Hip Hop",
            "UK Funky: Electronic",
            "UK Garage: Electronic",
            "UK Street Soul: Funk · R&B · Soul",
            "Unblack Metal: Pop · Rock",
            "Underground Hip Hop: Hip Hop",
            "Uplifting: Electronic",
            "Uplifting Trance: Electronic",
            "Urban: Hip Hop",
            "Urban Contemporary: Hip Hop",
            "Vallenato: Latin",
            "Vaporwave: Electronic",
            "Viennese Waltz: Other",
            "Viking Metal: Pop · Rock",
            "Vis-Pop: World",
            "Visual Kei: World",
            "Vocal: Other",
            "Vocal House: Electronic",
            "Vocal Jazz: Jazz",
            "Vocal Trance: Electronic",
            "Volksmusik: World",
            "Waiata: World",
            "Waltz: Other",
            "Wedding Cantata: Other",
            "West Coast Hip Hop: Hip Hop",
            "West Coast Jazz: Jazz",
            "West Coast Swing: Other",
            "Western Classical Music: Classical",
            "Western Country: Blues · Country · Folk",
            "Western Swing: Blues · Country · Folk",
            "Witch House: Electronic",
            "Wonky Pop: Pop · Rock",
            "World: World",
            "World Fusion: World",
            "World Music: World",
            "Worldbeat: World",
            "Yacht Rock: Pop · Rock",
            "Yemenite Jewish: World",
            "Yé-Yé: Pop · Rock",
            "Zamba: World",
            "Zamrock: World",
            "Zarzuela: World",
            "Zemer Ivri: World",
            "Zeuhl: Pop · Rock",
            "Zouk: World",
            "Zydeco: Blues · Country · Folk"});
            this.checkedListBox3.Location = new System.Drawing.Point(17, 17);
            this.checkedListBox3.MultiColumn = true;
            this.checkedListBox3.Name = "checkedListBox3";
            this.checkedListBox3.Size = new System.Drawing.Size(308, 334);
            this.checkedListBox3.TabIndex = 0;
            // 
            // tabbedTagger
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(372, 410);
            this.Controls.Add(this.tabControl1);
            this.Name = "tabbedTagger";
            this.Text = "tabbedTagger";
            this.tabControl1.ResumeLayout(false);
            this.tabMoods1.ResumeLayout(false);
            this.tabOccasions2.ResumeLayout(false);
            this.tabGenres3.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabMoods1;
        private System.Windows.Forms.CheckedListBox checkedListBox1;
        private System.Windows.Forms.TabPage tabOccasions2;
        private System.Windows.Forms.TabPage tabGenres3;
        private System.Windows.Forms.CheckedListBox checkedListBox2;
        private System.Windows.Forms.CheckedListBox checkedListBox3;
    }
}